### ISSUE TITLE
Generate documentation

### ISSUE THREAD

**Issue by DustinMEastway** [DustinMEastway/tstack#59]
Generate documentation using the JSDocs in the code using the same tool that the Angular team uses (dgeni). Smaller cards will be created to facilitate the parts required to make this happen while this epic will tack overall progress.
- [x] #60 Create the Dgeni documentation framework
- [x] #61 Replace the existing documentation with code pulling from the generated files
- [x] #62 Create the components required to display the sections in the documentation
- [x] #63 Incorporate Markdown files into package descriptions
- [x] #64 Allow examples to be added to documentation
- [x] #65 Create remaining document processors
